### ISSUE TITLE
JAWS 2019 bulleted list display differences

### ISSUE THREAD

**Issue by mcourcel** [FreedomScientific/VFO-standards-support#143]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Go to http://www.google.com
> 2. Shift-Tab back to the About link

### Expected result

> What did you expect to happen?

### Actual result

> What actually did happen?

### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

#### Browser and version:

First visit https://t.co/9u9HsBg6xx with JAWS 2019 and Chrome.  Under the description, the bulleted list will be blank.  Do the same thing with JAWS 2018 and Chrome and the bulleted list will work just fine.

**Comment by jducrot** [comment]
The list of features is not being picked up by JAWS (tested with JAWS 20) because the app developer did not use HTML list markup (e.g. <ul> and <li> elements) to build this list. It visibly appears to be a list, but it's really a series of paragraphs (e.g. <p> elements) starting with a bullet icon so this is not an issue with JAWS.

![image](https://user-images.githubusercontent.com/280674/82460619-67259480-9a87-11ea-898e-95fd60266398.png)
![image](https://user-images.githubusercontent.com/280674/82460732-87555380-9a87-11ea-9e03-145bc33335a1.png)
