### ISSUE TITLE
Jaws read aria-hidden heading inside bootstrap modal.

### ISSUE THREAD

**Issue by ejazahmedmohammad** [FreedomScientific/VFO-standards-support#156]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
1. Open the code provided in Code pen in IE.
2. Click on Open Modal.  
> Example:
> 1. Go to http://www.google.com
> 2. Shift-Tab back to the About link

### Expected result

> What did you expect to happen?
Jaws will read only "Visibile to screen reader" Heading
### Actual result

> What actually did happen?
Jaws reads "Hidden to screen reader" also.
### Example
https://codepen.io/ejazahmedmohammad/pen/Vqzyym
> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

#### JAWS version and build number
18.0.2945
 
#### Operating System and version
Windows 7 Enterprise Service pack 1

#### Browser and version:
IE Version 11.0.9600
updated Vesrion: 11.0.95

**Comment by stevefaulkner** [comment]
This is occuring because what is being announced is the accessible name for 
```
<div tabindex="-1" class="modal fade in" id="addIncomeModel" role="dialog" aria-hidden="true" style="display: block;" data-keyboard="false" data-backdrop="static" data-node-name="addIncomeModel">
```
In the abscence of an explicit accessible name being provide via `aria-label` or `aria-labelledby` the text content of the `dialog` is used as the accessible name for the `dialog` In IE. `aria-hidden` has no effect upon the accessible name calculation, Refer to [Hiding Content Has No Effect on Accessible Name or Description Calculation](https://www.w3.org/TR/using-aria/#hiding-content-has-no-effect-on-accessible-name-or-description-calculation).
