### ISSUE TITLE
JAWS reads in DOM order when its parent is float positioned

### ISSUE THREAD

**Issue by AvaniReddy** [FreedomScientific/VFO-standards-support#165]
JAWS is reading it in the incorrect order than they appear in UI.
JAWS reads in DOM order rather than they appear in UI when its parent is positioned using float positioning.

Observed:
If UI is displayed in the below order:
-> Label
-> required icon
-> help-text icon

then JAWS reads in the below order:
- > help-text icon
- > required icon
-> Label

Expected
JAWS should read in the same order as it is displayed in the UI

**Comment by jaychewy** [comment]
If my understanding is correct, JAWS and other screen readers always read in the order of the DOM, not in the visual order. Because of this, float might not work well in this situation. It's best to keep the DOM order in the logical order as it needs to read, then use CSS flex or grid to style the visual order.

**Comment by scottaohara** [comment]
@jaychewy is correct. JAWS is correctly reading the DOM order and ideally the markup would change to reflect the order in which it was meant to be parsed.
