### ISSUE TITLE
JAWS listing issue for list boxes

### ISSUE THREAD

**Issue by pmvrkris** [FreedomScientific/VFO-standards-support#166]
JAWS 2018 on IE is not listing the comboboxes with listboxes properly. 

Go to the sample page for the comboboxes shared by W3C, http://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html 

Press CTRL + INSERT + E (To list form elements) or CTRL + INSERT + C. (To list comboboxes)

JAWS is listing them as Unlabelled Edit Combo in the first place and is listing them as unlabelled in teh second instance.

**Comment by lamador** [comment]
The issue was reproduced using the latest version of JAWS (2020.2004.66), IE11 (11.836.18362.0), Chrome (83.0.4103.97 (Official Build) (64-bit)), and Firefox (77.0.1 (64-bit)).  The latest version of NVDA also produced the same results with the aformentioned browsers.

Although still in draft status, the [APG 1.2 combobox](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-both.html) is a more stable pattern across the board than the one used in APG 1.1.
