### ISSUE TITLE
JAWS auto-forms mode is not recognizing the comboboxes with list boxes. 

### ISSUE THREAD

**Issue by pmvrkris** [FreedomScientific/VFO-standards-support#167]
JAWS 2018 is not moving to the auto-forms mode on comboboxes in IE

Navigate to the http://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html and navigate to the comboboxes via tabbing and JAWS is not recognizing them as form elements (though those are listed as part of the form elements CTRL + INSERT + E) and hence those are not editable by default and the user has to manually move to forms mode.

**Comment by lamador** [comment]
The issue was reproducible using the latest version of JAWS (2020.2004.66) and IE11 (11.836.18362.0) on Windows 10.  More specifically, JAWS does not enter forms mode when the any of the three combobox fields obtain focus using the Tab key and announces the controls as "ARIA 1.0 Combobox Without Autocomplete Link".
