### ISSUE TITLE
[Jaws2018 + IE 11] Aria-label of buttons under 1 div read all at once for the first time

### ISSUE THREAD

**Issue by ShardulGhusey** [FreedomScientific/VFO-standards-support#18]
> Jaws reads aria-label of all the buttons in a div at once when one of its button gets focus for the first time
> Please check the mentioned codepen url

### Expected result
The aria-label of button which has focus should only be read

### Actual result
The aria-label of all the buttons in a div are read at once for the first time when one of its button gets focus

### Additional Information
Verified the the behavior with Jaws + Firefox & it is working as expected.
In the codepen just remove the divs inside the buttons 
then the Jaws will read it correctly. It is the div which affects jaws only on IE 11. 

#### JAWS version and build number
Jaws version 2018(build 1710.36ILM)

 #### Operating System and version
Windows 10 

#### Browser and version:
IE 11 -- 11.674

`[https://gist.github.com/ShardulGhusey/e2c610d4b328d4d93e7bee2463e42831](url)

**Comment by stevefaulkner** [comment]
@ShardulGhusey this is an interesting one. In the test case because you have `tabindex=-1` on the container `div` it is exposed in the accessibility tree (in IE) as a grouping object with an accessible name:
> MSAA
> accName: Button1 Button2;
> accRole: grouping;

So JAWS is correctly announcing what is exposed in the [accessibility tree](https://developer.paciellogroup.com/blog/2015/01/the-browser-accessibility-tree/). Adding `tabindex` to an element in IE makes it into an [accessible element](https://msdn.microsoft.com/en-us/library/gg701963%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#Making_Nonaccessible_Elements_Accessible)

So JAWS is doing what is expected.

**Comment by ShardulGhusey** [comment]
Thank you @stevefaulkner  role=presentation worked for me. Your investigation helped us in fixing some other issues as well. Thanks for your prompt response 👍

**Comment by StommePoes** [comment]
Thank YOU @ShardulGhusey for filing these, we can all read them for when we run into these ourselves!
