### ISSUE TITLE
Jaws 2018 Every 3rd row of my table acts differently

### ISSUE THREAD

**Issue by JeffKochuk** [FreedomScientific/VFO-standards-support#207]
### Summary

https://codepen.io/anon/pen/VJYaWq

In a table with buttons that handle the sort on the top and links to another page on the left, every 3rd row says "Name Change Sorting for ..."

### Expected result
Every row acts the same: Column header is just "Name".

### Actual result

Every 3rd row says "Name Change Sorting for ..."

### Example

Navigate through this table here.
https://codepen.io/anon/pen/VJYaWq

#### JAWS version and build number
JAWS version - 2018.1811.2 ILM
 
#### Operating System and version
-Windows 10 Enterprise (64-bit) 

#### Browser and version:
Version 74.0.3729.169 (Official Build) (64-bit) - google chrome

**Comment by JAWS-test** [comment]
In my opinion, this is not a JAWS bug. I hear the long output (with JAWS 2019) in every row and not only in Chrome, but also with IE 11 (but not with Firefox).
The buttons in the column headings are labelled with "Set the sorting for [name] column to descending" by aria-label.
The column headers are also output when you navigate through the table. The output is therefore correct.

There are three solutions to the problem:
* Use links without additional labels in aria-label and use aria-sort to specify the sorting direction (https://www.w3.org/TR/wai-aria-practices-1.1/#gridAndTableProperties_sort). With links in column headings it is clear to every user that they are used for sorting.
* Do not place the interactive elements in the column headings, but e.g. in the second row or outside the table.
* Mark the column headings with the abbr attribute (https://html.spec.whatwg.org/multipage/tables.html#attr-th-abbr). In this case, only the content of the abbr attribute is output during table navigation. However, this may only work with tables and not with ARIA grids.

Note: You use a grid (role=grid) instead of a table. This means that within the table only the arrow key navigation must be possible. If this is not implemented by JavaScript, please use a normal table without ARIA roles or role=table instead of role=grid. In addition, there are other things to consider in connection with role=grid, see: https://www.w3.org/TR/wai-aria-practices-1.1/#grid

**Comment by lamador** [comment]
Not reproducible using the latest version of JAWS (2020.2004.66) and Chrome (83.0.4103.97 (Official Build) (64-bit)) in Wndows 10.
