### ISSUE TITLE
Use of aria-describedby causes braille displays to print a different message than that spoken

### ISSUE THREAD

**Issue by arodenbeck** [FreedomScientific/VFO-standards-support#31]
When arrowing down through a web page, elements with aria-describedby cause a flash message on braille displays that is not spoken aloud. The display shows "msg Use JawsKey+Alt_R to read descriptive text". Since this is a flash message, it eventually does get replaced by the text read aloud, but this delay causes a significant slow down in navigating pages with braille alone.

Steps to reproduce:
1. Go to https://twitter.com/home
2. Do a JAWS find for "Reply"
3. This happens for reply buttons which have a reply count greater than 0. If the first "Reply" button applies to a tweet which has not been replied to, press F3 to search again.

Expected behavior:
The speech should read aloud "Reply X button". The braille display should show "Reply X". (Where X represents the number of replies.)

Actual behavior:
Speech reads aloud "Reply X button", but the braille display shows "msg Use JawsKey+Alt+R to read descriptive text".

Operating System: Windows Version	10.0.16299 Build 16299
Browser: Firefox ESR - 52.5.0 64-bit
Browser: Chrome Version 63.0.3239.84 (Official Build) (32-bit)
JAWS: Version 2018 (build 1712.10 ILM)

**Comment by hanshillen** [comment]
This seems more like a feature request than a defect, although it's not entirely clear what the best solution for this improvement would be. 

The expected behavior in your description implies that you would prefer the flash message to not appear at all when reading content with aria-describedby in virtual mode, which is actually similar to how the voice output works (the describedby text is ignored in this scenario unless the element with aria-describedby is actually keyboard focused or JAWSKEY + TAB is pressed). But this solution would remove a potentially useful feature for Braille display users (the information that there is descriptive text and how to get to it).

Maybe it would be a better solution to have the descriptive text itself be inserted after the element with aria-describedby, in both voice and Braille? Or have the "msg Use JawsKey+Alt+R to read descriptive text" message be added behind the element description, rather than as a flash message which obscures that element for 5 seconds?

We should probably figure out the desired behavior before filing a bug for this, so anyone ifeel free to add your opinion here.

**Comment by arodenbeck** [comment]
Maybe this is getting way off base, but I think the behavior for dealing with aria-describedby could be updated. In my experience, this attribute generally provides additional information to a field, and in speech is read when the element gains focus. The message that there is descriptive information seems redundant, and adds extra chatter.
Thinking along those lines, maybe presenting the information in braille immediately after the label would more closely parallel the voice experience. At the very least, I like your idea of putting the help message after the label, so that the label text is not obscured by the flash message.

**Comment by arodenbeck** [comment]
In playing more with this issue, it seems as if braille already performs the same as speech. The descriptive text is placed in the buffer after the element, even with braille. Does this behavior ever vary? If not, displaying the flash message doesn't seem to accomplish anything, other than obscuring the very text you intend to display. I have experimented with the key command as well, but I have not noticed it doing anything.
Finally, and here is where the bug exists, speech does not present the message. I turn off these types of messages, but the fact I prefer to not be bothered by the message does not seem to be honored in braille.
