### ISSUE TITLE
JAWS announce selected disable element as Not selected in multiselectable listbox

### ISSUE THREAD

**Issue by glushkova91** [FreedomScientific/VFO-standards-support#341]
### Summary

JAWS announce selected disable element as Not selected in multiselectable listbox
 Example:
1. Go to https://stackblitz.com/edit/angular-lrjjwa?file=src/app/list-selection-example.ts
2. Enable JAWS SR 
3. Focus on disabled but selected row
4. Check the result: SR announces that item is Not selected

### Expected result

SR should announce the item is selected

### Actual result

SR announces the selected disabled item is NOT selected

### Example

https://stackblitz.com/edit/angular-lrjjwa?file=src/app/list-selection-example.ts

#### JAWS version and build number
JAWS 2019.1907.42 

 
#### Operating System and version

Windows

#### Browser and version:

Chrome

**Comment by JAWS-test** [comment]
I cannot confirm the problem.

I have tested with Firefox and Chrome, JAWS 2019 and Windows 8:
* Arrow key navigation in form mode: disabled is output correctly
* Read with arrow keys: disabled list entries are not output at all. However, this corresponds to the output of an HTML selection list, where disabled list entries are not perceptible with JAWS.

See for example:
```
<select multiple>
	<option>1
	<option selected>2
	<option selected disabled>3
	<option disabled>4
</select>
```

**Comment by glushkova91** [comment]
> Although recommended at https://w3c.github.io/aria-practices/#kbd_disabled_controls, it is questionable whether it makes sense for disabled list entries to receive the focus.

Since it's a recommended approach according to w3.org https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls I think it makes sense

**Comment by scottaohara** [comment]
Confirming this behavior still occurs with latest Chrome/Edge and JAWS 2020 (june release).

Reviewing what's being exposed at the platform level, this appears to be an issue with Chromium as the "selected" state is exposed for the enabled option, but is _not_ for the disabled option.

For instance, testing this with Chrome and VoiceOver, the listbox will report only a single item as being selected, when both are in the selected state.  Testing with Safari and VoiceOver, the listbox will report as two items being selected.

Per those results, I'm labeling this as a chrome issue, and not a bug with JAWS.  I would recommend an issue be filed with Chromium, though I personally can't say whether or not this is a "bug" or if it was a choice to actively not expose a selected state for a disabled option.

Regarding focusability here, i'm leaning more towards @JAWS-test's questioning of this behavior, as it does go against the default behavior of the native HTML expectations.  I understand why ARIA Practices recommends this, but it's worth remembering that the APG is a note. Thus any recommendation there is not normative, and may rather represent the behavior the note considers ideal, rather than actual behavior.
