### ISSUE TITLE
JAWS 18 calls all header tags banners

### ISSUE THREAD

**Issue by StommePoes** [FreedomScientific/VFO-standards-support#35]
### Summary

This is a two-parter: one is a JAWS bug, the other is an observation of an IE bug.

JAWS reads all &lt;header&gt; tags as banner regions, regardless of the &lt;header&gt; nesting level. According to <a href="https://www.w3.org/TR/html52/sections.html#the-header-element">the spec on header</a>, only those scoped to the body of a document or application should get the banner role, and that any document/app <a href="https://www.w3.org/TR/wai-aria-1.1/#banner">SHOULD only have 1</a> banner role.

 1. Go to https://tink.uk
 2. 'r' around the regions OR just arrow through the page content

The page has &lt;article&gt;s and within those are &lt;header&gt;s, which should not receive banner roles.

### Expected result

I should only encounter the main, nav, complimentary landmarks on the page.

### Actual result

After the main landmark I encounter "article banner" as landmark stops using the landmark shortcut 'r'. Arrowing through the page reads out both the articles and their "banners" inside them.

### Additional Information

Interestingly, Internet Explorer seems has some bug which interlaces with this-- in both JAWS and NVDA, all &lt;header&gt;s are read out as banners. NVDA does not do this in Firefox nor Chrome. JAWS however calls all &lt;header&gt;s banners in all browsers, not just IE. This means testing whether the JAWS bug is fixed requires checking all the browsers.

#### JAWS version and build number

18.0.4534

 
#### Operating System and version

Windows 7 Professional/Service Pack 1

#### Browser and version:

Tested in IE11, Firefox ESR (52.something), Chrome 63.

**Comment by stevefaulkner** [comment]
@hanshillen i suggest looking into jaws bugzilla as this may be filed bug

**Comment by hanshillen** [comment]
The banner issue seems to have been resolved in JAWS 2018. It no longer announces the banners In IE11, Edge, Chrome 64 and Firefox ESR 52, when using virtual arrow key navigation or when using the R shortcut.

JAWS 2018 does still traverse the articles themselves when navigating via the R key. I'm guessing this is more of a design choice than a bug on JAWS' part. The JAWS documentation describes it as a 'landmark / region' shortcut, although article is a document role. The spec says the article role is not a navigational landmark, but also says AT can provide a feature to navigate article hierarchies. I suppose we can put in a feature request to have two separate shortcuts: one for landmarks only and one for articles. @stevefaulkner (or anyone else) what do you think? 

I also noticed that JAWS' region list (JAWSKEY + CTRL + R) still incorrectly lists the banner region for each article, so I will file a separate bug for that.

**Comment by StommePoes** [comment]
I don't mind having articles available for navigation, but I'm not any representative JAWS user. Some people mark up blog posts lists with article though and then it's nice, I get a better idea of what the dev was thinking qua structure, which navving by headings alone doesn't necessarily give.

**Comment by stevefaulkner** [comment]
@StommePoes navigation by `<article>` and an associated list of `article`'s in a page will be available soon in JAWS 2018.

**Comment by ggordon-vfo** [comment]
This isn't actually currently fixed in JAWS 2018 but rather is masked by the fact that by default JAWS no longer identifies Banner or Content Info regions. However, even if identification of selected regions is disabled, using the letter r to navigate by region actually stops on their content. So in the case of the articles in the blog in question, JAWS isn't stopping on the articles but is instead stopping on the banners at the start of each.

You can use Insert+f2, select SettingCenter, and from that app search for Web Verbosity. If you change it to High (Medium is the default) identification of Banner/Content Info will come back.
We have a fix that will be part of the March JAWS update that unconditionally ignores Banner and Content Info regions that aren't immediate children of the body.

We'll also be reassigning the letter o, now reserved to move between objects, to move between articles instead.

**Comment by stevefaulkner** [comment]
Internal bug filed: Bug 99866 - JAWS includes nested header and footer elements in region navigation

**Comment by ggordon-vfo** [comment]
Fixed in JAWS 2018 March 2018 update. Also applies to JAWS 2019.
