### ISSUE TITLE
alt attribute is output as button label (Chrome)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#360]
### Summary

* Go to https://codepen.io/jaws-test/pen/rNabLmW
* navigate with tab key to the button, read with virtual cursor or use quick navigation (B) or element overview (INS+Ctrl+B)

### Expected result

Text content is output as label

### Actual result

alt attribute and not the text content is output as label

The problem occurs only in Chrome+JAWS and not in IE or Firefox. It also does not occur with NVDA+Chrome.

I know that alt on button is not allowed. Unfortunately there are frameworks that implement this

#### JAWS version and build number
JAWS 2019
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 79.0.3945.130

**Comment by scottaohara** [comment]
confirmed still happening with latest jaws 2020 / version of chrome.

chrome correctly exposes accessible name as text content of the button.  JAWS ignores the exposed accessible name and uses the value of the invalid `alt` on the button element.

This is a rather odd quirk, but is also specifically due to author error...

**Comment by scottaohara** [comment]
while this is a jaws bug, it's caused by author error.
