### ISSUE TITLE
JAWS will not enter forms mode with <input type="number"> in Edge (pre-Chromium)

### ISSUE THREAD

**Issue by davidakennedy** [FreedomScientific/VFO-standards-support#369]
## Summary

JAWS will not enter forms mode when focused on an `<input type="number">` input. Even after trying to manually enter forms mode.

See test case: https://codepen.io/davidakennedy/pen/VwLvVvX

It also can be experienced on any of the fields here: https://thepaciellogroup.github.io/AT-browser-tests/test-files/input-number.html

## Expected result

JAWS should enter forms mode so I can type normally in the field.

## Actual result

Forms mode doesn't enable automatically, and pressing enter (laptop layout) doesn't enable it either.

### Example

See above.

## Additional Information

- JAWS version and build number: 2019.1912.1ILM
- Operating System and version: Windows 10
- Browser and version: Microsoft Edge 44.183.62.449.0

I also tested this in IE 11 and new Edge (Chromium) and it's not an issue.

**Comment by JAWS-test** [comment]
My experience with Edge and JAWS is that it makes more sense to report what works than to report what doesn't. There are countless bugs with JAWS and Edge, so this combination does not make sense. To my knowledge, Freedom Scientific no longer fixes these bugs because the old Edge has been replaced by Edge Chromium

**Comment by scottaohara** [comment]
marking as wont fix due to being legacy edge issue
