### ISSUE TITLE
Aria-roledescription not read 

### ISSUE THREAD

**Issue by JasonAment** [FreedomScientific/VFO-standards-support#376]
### Summary
Jaws 2019:
Aria-roledescription not read when the user lands on a link in 2019. Aria-label is not read in any case.
Jaws 2020:
Aria-roledescription not read when the user lands on a link or button in 2020. Aria-label is not read in any case.

### Example using a link or a button:
1. 1. Using IE11 on Windows 10, Jaws 2019
2. Go to https://cdpn.io/JasonAment/debug/XWbeOeG
3. Tab to the link (Note the screen reader output)
4. Tab to the button (Note the screen reader output)

### Expected result: 
aria-roledescription is read by the screen reader, regardless of the focused element.
aria-label is read by the screen reader

### Actual result: 
Jaws 2020: aria-roledescription is not read by the screen reader, regardless of the focused element.
Aria-label is not read by the screen reader.
Jaws 2019: aria-roledescription is not read by the screen reader when the focus lands on a link, but is read when the focus lands on a button.  Aria-label is not read by the screen reader.
Note: that while the "region 2" is read when the focus lands on the button, the button role is overriden  [Bug #288](https://github.com/FreedomScientific/VFO-standards-support/issues/288)
aria-label is not read by the screen reader.

### Example
https://cdpn.io/JasonAment/debug/XWbeOeG

#### JAWS version and build number
Jaws 2019, 2019.1912 ILM
Jaws 2020, 2020.1912.11 ILM

#### Operating System and version
Windows 10, version 1803 (build 17134.1304)

#### Browser and version:
IE11 version 11.1304.17134.0

**Comment by JAWS-test** [comment]
In your example, the link and button have no ARIA attributes, only the enclosing section. Therefore, the first question would be: Is an enclosing region output at all in IE 11 when an element in it gets the focus? As far as I know: No. That's why I don't think the output in IE 11 has anything to do with aria-roledescription and aria-label. Furthermore, the question would be whether it makes sense at all to output the enclosing regions with tab navigation. In Chrome and Firefox, this behavior often leads to a very long output

**Comment by ferllings** [comment]
Works fine on Chrome 81/ Firefox 77 With Jaws 2019/2020. Also tested with https://a11ysupport.io/tests/html/aria_roledescription_with_html_button.html.
