### ISSUE TITLE
Navigation between radio buttons doesn't work

### ISSUE THREAD

**Issue by yugu0114** [FreedomScientific/VFO-standards-support#448]
### Summary

> We have layout table as container. It has role='presentation'. If we place radio buttons in <td> than a user can't change visible focus with Jaws (virtual cursor mode is on).  It can be issue for motoric+visual impared group of people.
> 
> Example:
> 1. https://jsbin.com/resawicuxi/1/edit?html,css,output
> 2. Try to change value to 'Other'

### Expected result

> Value is changed by arrow keys, focus is changed also

### Actual result

> Focus is not changed. Value is changed only after pressing Enter key. It caused by <table> but it has role='presentation' and we can't replace it with <div>.

### Example

> https://jsbin.com/resawicuxi/1/edit?html,css,output

#### JAWS version and build number

2020.2008.24 ILM
 
#### Operating System and version

Win 10

#### Browser and version:
IE v. 11.1082.18362.0 /  update v. 11.0.210 (KB4577010)
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by stevefaulkner** [comment]
In virtual cursor mode the radio buttons can be navigated and checked (upon space or enter).
In order to pass through keystrokes to the browser and have selection change on focus you need to press enter on the first radio button, this will put JAWS into forms mode.
This article may be helpful [Understanding screen reader interaction modes](https://tink.uk/understanding-screen-reader-interaction-modes/)
