### ISSUE TITLE
JAWS2020 doesn't trigger keyup event on radio buttons

### ISSUE THREAD

**Issue by Leuvarden** [FreedomScientific/VFO-standards-support#477]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Using IE11 or Chrome, Go to https://jsbin.com/yudoruhohu/edit?html,js,output
> 2.  Tab through the radio buttons
> 3. Press Space on any radio button to see the alert

### Expected result

> Alert is shown when pressing Space or Enter on the radio button

### Actual result

> Alert is shown after pressing Enter, but does not appear on Space

### Example

> https://jsbin.com/yudoruhohu/edit?html,js,output

#### JAWS version and build number

JAWS 2020.2006.12 ILM
 
#### Operating System and version

Microsot Windows 10 Enterprise
10.0.18363 Build 18363

#### Browser and version:

Chrome 87.0.4280.88
IE11 11.1082.18362.0

**Comment by JAWS-test** [comment]
I have tested it with current Chrome and JAWS 2020.2008 and the problem does not occur in my test environment:

* in forms mode, Enter and Space trigger the key event
* in reading mode (virtual cursor), Enter and Space do not trigger the key event

Important to know: 
* Radio buttons are the only elements where the mode (reading mode or forms mode) depends on the mode of the previously focused element
* JAWS intercepts all keyboard input and, depending on the mode and the key, either sends it to the browser or uses it for itself
* JAWS converts key events to click events for certain elements (default setting, this setting can be changed in JAWS settings center, INS+6 > Link activation). But that shouldn't be a problem, because a website must work with mouse and keyboard. I.e. if it is implemented correctly, the page uses device-independent event handlers or simultaneously mouse and keyboard event handlers

**Comment by stevefaulkner** [comment]
@Leuvarden as @JAWS-test stated, this apparent issue is related to the JAWS mode that you use to interact with the radio buttons. In virtual cursor mode typically keystrokes are not sent to the browser they are intercepted by JAWS. This occurs because JAWS listens for the keystrokes to use for navigation of non interactive content. On interactive elements some keystrokes are passed through to the browser if they are typical for use with the type of control. For radio buttons the usual interaction is for selection to change on focus. Use of the `space` key is not expected. When the enter key is pressed when a radio button has focus you may here a beep as JAWS switches to forms mode. When in forms mode the space key press is passed through to the browser and the alert is displayed.
