### ISSUE TITLE
div with tabindex=-1 is output as grouping element

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#497]
### Summary

1. Go to https://codepen.io/jaws-test/pen/NWbbEbB
2. Tab to the input fields
 
### Expected result

No output of a group label

### Actual result

* The entire content of the div element is output as a group label. 
* If the div has an explicit label, this is output as a group label

The problem never occurs with NVDA.

The problem occurs with IE 11 and Firefox together with JAWS only if the div has an explicit label.

#### JAWS version and build number
2021.2012.57
 
#### Operating System and version
Windows 10

#### Browser and version:
Current version of IE 11, Chrome and Firefox

**Comment by StephenBeckettTPGi** [comment]
Confirmed; also occurs in Edge.

**Comment by bdglide** [comment]
Confirmed in Chrome with JAWS 2021.2105.53

**Comment by BenKeyFSI** [comment]
This is not a bug.

When JAWS speaks a focus change in a web browser it calls the GetFocusChangeDepth function to determine whether ancestor objects should be spoken and if so how many ancestor objects should be spoken. The GetFocusChangeDepth function operates by examining the Cached MSAA Data and comparing the Cached MSSA Data for the current focused object with the Cached MSSA Data for the previous focused object. The GetFocusChangeDepth function uses the following algorithm to calculate the depth. 

```
int curIndex = current->AncestorCount();
int prevIndex = previous->AncestorCount();
for (; curIndex > 0 && prevIndex > 0; curIndex--, prevIndex--)
{
  bool sameObject = (AreTheseTheSameObject(current, curIndex, previous, prevIndex) ? true : false);
  if (!sameObject)
  {
    return (curIndex);
  }
}
```

The FocusChangedEvent function in ia2browser.jss, which is used by Chrome.jss, Firefox.jss, and Skype.jss calls the GetFocusChangeDepth function to obtain the depth and passes the value returned by the function to the DoSayObjectTypeAndTextFromLevel function. The DoSayObjectTypeAndTextFromLevel function does the following.

```
while (level > 0)
  /* Some filtering to avoid excessive speech. */
  SayObjectTypeAndText(level)
  level = level - 1
EndWhile
```

All this is by design and correct.

On the [Full Test Page](https://codepen.io/jaws-test/full/NWbbEbB), the GetFocusChangeDepth function returns 4 when focus moves from the User Menu button to the label1 input. Then when focus moves between items within the elements contained within the "div with tabindex=-1" the GetFocusChangeDepth function returns 0. Then when focus moves between the last item in within the "div with tabindex=-1" and the first item in the "div with tabindex=-1 and role=presentation" the GetFocusChangeDepth function returns 1.

Now you may be wondering why the filtering code I mentioned above does not ignore the object.

The following is the MSAA Information for the "div with tabindex=-1" as obtained using [Microsoft Inspect]()

```
How found:	Selected from tree...
ChildId:	0
Interfaces:	
Impl:	Remote native IAccessible
Name:	"1 2 div with tabindex=-1"
Value:	""
Role:	grouping (0x14)
State:	focusable (0x100000)
Location:	{l:1383, t:205, w:1899, h:35}
Selection:	
Description:	[null]
Kbshortcut:	[null]
DefAction:	[null]
Help:	[null]
HelpTopic:	""
ChildCount:	4
Window:	0x80D8C
FirstChild:	"label1" : editable text : focused,focusable
LastChild:	" div with tabindex=-1" : text : normal
Next:	"3 4 div with tabindex=-1 and role=presentation" : grouping : focusable
Previous:	[null]
Left:	[Error: hr=0xFFFFFFFF80004001 - Not implemented]
Up:	[Error: hr=0xFFFFFFFF80004001 - Not implemented]
Right:	[Error: hr=0xFFFFFFFF80004001 - Not implemented]
Down:	[Error: hr=0xFFFFFFFF80004001 - Not implemented]
Other Props:	Object has no additional properties
Children:	"label1" : editable text : focused,focusable
	"1" : push button : focusable
	"2" : push button : focusable
	" div with tabindex=-1" : text : normal
Ancestors:	"CodePen - div with tabindex" : document : read only,focusable
	none : document : normal
	none : grouping : normal
	none : grouping : normal
	"div with tabindex" : document : read only,focusable
	"div with tabindex" : window : focusable
	"div with tabindex - Google Chrome" : pane : normal
	"div with tabindex - Google Chrome" : window : sizeable,moveable,focusable
	"Desktop 1" : client : focusable
	"Desktop 1" : window : focusable
	[ No Parent ]
```

As you can see, this object has the MSAA Role of grouping (0x14). Objects with the MSAA Role of grouping (0x14) are often used a Group Boxes. JAWS speaks Group Boxes because they provide necessary context to help users know what a given control is used for.
