### ISSUE TITLE
[JAWS+IE11]Reading Checkbox and Buttons names as 'blank' inside <li> with role='treeitem' 

### ISSUE THREAD

**Issue by rp-19** [FreedomScientific/VFO-standards-support#50]
[JAWS accessibility test.txt](https://github.com/FreedomScientific/VFO-standards-support/files/1723143/JAWS.accessibility.test.txt)
### Summary
> Steps:
> 1. open the attached HTML in IE11 and JAWS
> 2. Jaws reads out the name of the checkbox and buttons as blank.
> P.S: It reads expected names at times, but not always. 

### Expected result

> Read the names of the checkbox and buttons as provided (Condition/Add Filter/Add Related Entity Filter)

### Actual result

> Jaws reads 'blank' for both the buttons and checkbox
### Example

> Attached HTML file
#### JAWS version and build number
Version 2018 (build 1710.42 ILM)

 
#### Operating System and version
Windows 10

#### Browser and version:
IE11

**Comment by jducrot** [comment]
@rp-19 the code you shared is behaving as you described in IE11 even using JAWS 20. However, I wouldn't expect JAWS 18 or 20 to handle this code properly because it is not following the WAI-ARIA guidelines for tree view widgets: https://www.w3.org/TR/wai-aria-practices-1.2/#TreeView. Could you share a scenario where adding an HTML element with a role="presentation" between a <ul> and its first <li> would be needed/beneficial?

I didn't run into any issues with IE11 + JAWS 20 interacting with this well-formatted tree view widget: https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-1/treeview-1a.html. However, when I adapted this example to contain buttons JAWS 20 still announces buttons as "blank" in IE11: https://cdpn.io/torcud/debug/bGVpwJx/XBAGRqQjWVXr

**Comment by JAWS-test** [comment]
https://cdpn.io/torcud/debug/bGVpwJx/XBAGRqQjWVXr = 403 error

Between ul and li there is a role=presentation.
But I wonder if a treeitem should / may contain buttons or checkboxes at all ...? The ARIA specification does not prohibit this, but actually the checkbox status is transmitted directly at the treeitem via aria-checked and how two different buttons within a treeitem should be operated is questionable
