### ISSUE TITLE
Context menu appearing in edge case for left hand users

### ISSUE THREAD

**Issue by anevins12** [FreedomScientific/VFO-standards-support#573]
![Untitled](https://user-images.githubusercontent.com/2318561/132317902-3dd6c7d9-9f27-4941-8131-59500dec2634.png)

### Summary
Left-hand users initiating click events via the space or enter key on fake radio buttons causes the right-click context menu to appear.

### Expected result
JAWS should initiate the left click event. In the codepen scenario nothing should happen.

### Actual result

The right click context menu appears.

### Example

1. Go to native mouse settings for the operating system;
2. Set primary click as right click;
3. Go to [this codepen](https://codepen.io/TPG/full/YzQpOQq);
4. Tab onto the fake radio button;
5. Press spacebar or enter.

#### JAWS version and build number
2021.2027.12

 
#### Operating System and version
Windows 10 Pro, 20H2

#### Browser and version:
Chrome 93.0

**Comment by JAWS-test** [comment]
With JAWS version 2021.2107.12, the problem does not occur after switching mouse buttons, although the cause is probably that JAWS converts the keyboard events to click events. However, this can be disabled in the settings (INS+6). I have also tested the problem in Firefox as well as with various elements (HTML and ARIA version of links, buttons, checkboxes, radiobuttons), but it never occurred

**Comment by anevins12** [comment]
I really appreciate the speed of your response and that you looked into this. 

Can I ask if you could try pressing the `ctrl` key just before the spacebar or enter key?

**Comment by anevins12** [comment]
I'll close this, thanks again for your help.
