### ISSUE TITLE
jqueryui autocomplete blocked to navigate with arrows 

### ISSUE THREAD

**Issue by bellawo** [FreedomScientific/VFO-standards-support#59]
### Summary

queryui autocomplete blocked to navigate with arrows 

Steps:
1. Go to https://jqueryui.com/autocomplete/
2. Type "a" in "Tags" field
3. navigate by arrows (down) untill "Haskell" item
4. the field will be blocked
you can do it with "l" till "Perl"

### Additional Information
I'm not sure if this is specifically a JAWS bug or Jquery ui bug 

#### JAWS version and build number
JAW 18.0.4532
chrome 64.0.3282.186
windows 10

**Comment by stevefaulkner** [comment]
@bellawo I can replicate, I think it has something to do with [JAWS auto-forms mode](http://www.freedomscientific.com/Training/Surfs-Up/Forms.htm) When the setting is changed to semi-auto forms mode, the issue goes away. When the list of auto complete options is navigated with auto forms mode set JAWS disables forms mode. This is because the dropdown list is not  considered a form control. The list is marked up as a `<ul>` with `<li>`'s rather than as a `listbox` with `option`'s. Contrast this with JAWS behaviour in auto-forms mode when [the list is marked up](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html) as `listbox/options`
<img width="493" alt="settings center - forms - with semi-auto forms mode radio button selected." src="https://user-images.githubusercontent.com/835859/38305351-85002002-3804-11e8-80c5-8e5293a64fd2.PNG">

**Comment by JAWS-test** [comment]
To keep JAWS in form mode, the list entries must be marked with listbox and option. However, this only applies to autocomplete lists that receive the focus. This is not the case with jquery.  The focus remains in the input field.   JAWS output occurs because the value in the input field is updated and because there is a live region. For this reason, the output occurs twice.  The reason why JAWS always leaves form mode at the 7th entry is very peculiar and requires further investigation. jquery's old autocomplete solution (without live region) was good accessible with JAWS.

The problem occurs in both Chrome and Firefox, but not in IE 11.

I think it should be checked whether the error is in JAWS or jquery. I don't think it makes sense to change the mode in the JAWS Settings Center, because the pages should work in JAWS' default mode.

In my opinion, the jquery autocomplete feature is widely used on the web and should work fine with JAWS.
