### ISSUE TITLE
JAWS reading heading when dropdown is being opened(IE11)

### ISSUE THREAD

**Issue by nikhil-compro** [FreedomScientific/VFO-standards-support#90]
### Summary

Steps to replicate 
1. Open Url in IE11 - https://jawsaccessibility.herokuapp.com/index.html
2. Start JAWS 
3. Click on blank area in ui(grey color) 
4. Press tab and then enter to open dropdown

### Expected result

Expected - only dropdown text should have been announced

### Actual result

Output - "Nam non metus diam........" text will be announced with dropdown text

### JAWS version
Replicable in JAWS 2018
 
#### Browser and version:
IE11

**Comment by nikhil-compro** [comment]
Seems like Issue is with when focus moves from one element to another. For example when we move from div 1 to div 2 and div 2 is parallel to div 1 or somewhere else(but not inside div 1) then jaws will announce the complete text of div 2 parent which has tabindex

**Comment by stevefaulkner** [comment]
@nikhil-compro This is due to an issue with how IE represents elements in the accessibility tree. When and element has a `tabindex` then it is included in the accessibility tree and the accessible name for that element is the child text, unless there is some other source for the accessible name provided. In the test case
`<div class="dummysample" tabindex="-1">` is presented as a grouping object in the accessibility tree with an accessible name of "Nam non metus diam. Mauris vehicula ac lectus eu pharetra" and is announced when the dropdown button receives focus.

Try adding `aria-label=""` (empty label) to the `div`. This provides an alternative 'null' label for the `div` and resolves the problem.
`<div class="dummysample" tabindex="-1" aria-label="">`

**Comment by nikhil-compro** [comment]
Thanks this fixed the issue.
